# -*- coding: utf-8 -*-
"""1. Caracterización LDA_GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ToYcJAlgXxSVCHPnWyucPs2ALUNcc4F-

**Caso de Estudio**
Se quiere evaluar la estructura de la distribución de las pérdidas mediante la utilización de las métricas de tendencia central y dispersión. Para la obtención de la distribución agregada de pérdidas, se utilizarán como referencia las variables:

* Monto (EAD): Indica el monto solicitado por un solicitante de crédito.
* Probabilidad de Default: Indica la probabilidad de que un solicitante de crédito entre en default a lo largo de la vigencia del crédito.
* LGD: Indica la garantia del crédito.

0. Se procede con la carga de las librerias de trabajo
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""1. Se procede con la carga de los datos y la obtención de la distribución LDA"""

nxl='/content/0. SolicitantesCrédito(USD).xlsx'
XDB=pd.read_excel(nxl,sheet_name=1)
XDB=XDB.dropna()

XDB=XDB.iloc[:,[25,33,35]]
XDB.head()

#Se procede con la obtención de la distribución LDA
LDA=XDB.iloc[:,0]*XDB.iloc[:,1]*(1+XDB.iloc[:,2])

"""2. Procedemos con la Gráfica de la Distribución Agregada de Pérdidas"""

LDA=pd.DataFrame(LDA)
LDAm=np.array(LDA.sample(n=len(LDA),replace=True))

plt.figure()
sns.histplot(LDA, kde=True, bins=10, color='green', alpha=0.5, label='LDA')
plt.legend()  # Para mostrar la leyenda
plt.grid()
plt.xlabel('Pérdidas')
plt.ylabel('Frecuencia')
plt.title('Distribución Agregada de Pérdidas')
plt.savefig("graficoxls4.png")
plt.show()

"""3. Se procede con la construcción de la página web"""

#Para la creación del HTML
html_content = """
<html>
<head>
<title>Distribución de las Pérdidas</title>
<style>
body { font-family: Arial; text-align: center; margin-top: 40px; }
img { max-width: 90%; height: auto; border: 1px solid #ccc; }
h1 { color: #003366; }
</style>
</head>

<body>

<h2>Gráfico</h2>
<p>Este gráfico muestra la distribución agregada de pérdidas</p>
<img src="graficoxls4.png">

</body>
</html>
"""

with open("resultadoxls4.html", "w") as f:
    f.write(html_content)

"""4. Se procede con la carga de los resultados en la plataforma GitHub Pages"""

import base64
import requests

token = ""
repo = "pfjapena/ProspectiveRisk"
headers = {"Authorization": f"token {token}"}

def upload_file(local_path, repo_path):

    print(f"--- Subiendo {local_path} → {repo_path} ---")             #Mensaje de la carga d elos archivos

    content = open(local_path, "rb").read()                           #Se lee cada uno de los archivos a subir

    encoded = base64.b64encode(content).decode("utf-8")               #Se codifican en código binario
    url = f"https://api.github.com/repos/{repo}/contents/{repo_path}" #Se actualiza la URL

    # 1. Verificar si el archivo existe (para obtener SHA)
    r = requests.get(url, headers=headers)                            #Verificación y actualización de los archivos existentes

    if r.status_code == 200:
        sha = r.json()["sha"]
        data = {
            "message": f"Actualizando {repo_path}",
            "content": encoded,
            "sha": sha
        }
        print("El archivo existe. SHA:", sha)
    else:
        data = {
            "message": f"Creando {repo_path}",
            "content": encoded
        }
        print("El archivo NO existe. Se creará.")

    # 2. Subir archivo
    r2 = requests.put(url, json=data, headers=headers)              #Se suben los archivos de trabajo

    print("Código:", r2.status_code)
    print("Respuesta:", r2.json())
    print("-------------------------------------------")

# SUBIR HTML Y PNG
upload_file("/content/resultadoxls4.html", "resultadoxls4.html")
upload_file("/content/graficoxls4.png", "graficoxls4.png")